apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: {{ .Values.host }}
    http:
     paths:
     - path: "/"
       pathType: Prefix
       backend:
         service:
           name: {{ .Release.Name }}-svc
           port:
             number: {{ .Values.port }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: wordpress-tls